### ISSUE TITLE
Get command-line tool working

### ISSUE THREAD

**Issue by thespacedoctor** [smmatthews/survey_simulator_post_processing#3]
Test command-line 'surveySimPP' and see if it works.

**Comment by smmatthews** [comment]
@thespacedoctor When running surveySimPP through the command line, I get the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/simpp/bin/surveySimPP", line 33, in <module>
    sys.exit(load_entry_point('surveySimPP', 'console_scripts', 'surveySimPP')())
  File "/opt/anaconda3/envs/simpp/bin/surveySimPP", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/anaconda3/envs/simpp/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'surveySimPP.__main__' has no attribute 'main'
```

**Comment by thespacedoctor** [comment]
Can you try and change this in setup.py:

```python
surveySimPP = surveySimPP.__main__:main
```

to this:

```python
surveySimPP = surveySimPP.surveySimPP.__main__:main
```

If that doesn't work can you push your changes to this branch and I'll clone and test

**Comment by smmatthews** [comment]
That didn't seem to work so I've pushed my changes. All the required packages are included in the setup file apart from sbpy. There's a problem with the current version and it introduces errors so we've been using the latest development version. There's some install instructions here: https://sbpy.readthedocs.io/en/latest/install.html

**Comment by thespacedoctor** [comment]
Can you add me as a collaborator on the project? I'll push some changes into a tmp branch and issue a pull request for you to review (Settings > Collaborators)

**Comment by smmatthews** [comment]
@thespacedoctor Just done!
